'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Bell } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Alert, EmptyState } from '@/components/ui/feedback';
import { markAllNotificationsRead, markNotificationRead } from '@/app/portal/actions';
import { SEVERITY_STYLES } from '@/lib/constants';
import { cn, formatRelative } from '@/lib/utils';
import type { Notification } from '@/lib/types';

/**
 * Notification feed.
 *
 * Notifications are generated by the database when an application's status
 * changes, so this list is the record of what actually happened to an
 * application — it never contains placeholder content.
 */
export function NotificationList({
  notifications,
  showMarkAll = true,
}: {
  notifications: Notification[];
  showMarkAll?: boolean;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const unread = notifications.filter((item) => !item.is_read);

  const handleRead = (id: string) => {
    setError(null);
    startTransition(async () => {
      const result = await markNotificationRead(id);
      if (!result.ok) {
        setError(result.error);
        return;
      }
      router.refresh();
    });
  };

  const handleMarkAll = () => {
    setError(null);
    startTransition(async () => {
      const result = await markAllNotificationsRead();
      if (!result.ok) {
        setError(result.error);
        return;
      }
      router.refresh();
    });
  };

  if (notifications.length === 0) {
    return (
      <EmptyState
        icon={Bell}
        title="No notifications yet"
        description="Updates about your application — submission, review, requests for more information and decisions — will appear here."
      />
    );
  }

  return (
    <div className="space-y-4">
      {error ? <Alert variant="error">{error}</Alert> : null}

      {showMarkAll && unread.length > 0 ? (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-slate-600">
            <span className="tabular font-semibold text-navy-900">{unread.length}</span>{' '}
            unread {unread.length === 1 ? 'notification' : 'notifications'}
          </p>
          <Button variant="secondary" size="sm" onClick={handleMarkAll} loading={pending}>
            Mark all as read
          </Button>
        </div>
      ) : null}

      <ul className="divide-y divide-slate-200 overflow-hidden rounded-lg border border-slate-200 bg-white">
        {notifications.map((notification) => {
          const severity = SEVERITY_STYLES[notification.severity] ?? SEVERITY_STYLES.info;
          const Icon = severity.icon;

          return (
            <li
              key={notification.id}
              className={cn('flex gap-3.5 px-4 py-4 sm:px-5', !notification.is_read && 'bg-navy-50/40')}
            >
              <span
                aria-hidden="true"
                className={cn(
                  'mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-full ring-1 ring-inset',
                  severity.className
                )}
              >
                <Icon className="size-4.5" strokeWidth={1.9} />
              </span>

              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-start justify-between gap-x-4 gap-y-1">
                  <p className="text-sm font-semibold text-navy-900">
                    {notification.title}
                    {!notification.is_read ? (
                      <span className="ml-2 inline-flex items-center rounded-full bg-emerald-600 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-white align-middle">
                        New
                      </span>
                    ) : null}
                  </p>
                  <time
                    dateTime={notification.created_at}
                    className="shrink-0 text-xs text-slate-500"
                  >
                    {formatRelative(notification.created_at)}
                  </time>
                </div>

                {notification.body ? (
                  <p className="mt-1 text-sm leading-relaxed text-slate-600">{notification.body}</p>
                ) : null}

                <div className="mt-2.5 flex flex-wrap items-center gap-x-4 gap-y-2">
                  {notification.action_url ? (
                    <Link
                      href={notification.action_url}
                      className="inline-flex items-center gap-1 text-xs font-semibold text-navy-800 hover:underline"
                    >
                      View details
                      <ArrowRight aria-hidden="true" className="size-3.5" />
                    </Link>
                  ) : null}

                  {!notification.is_read ? (
                    <button
                      type="button"
                      onClick={() => handleRead(notification.id)}
                      disabled={pending}
                      className="text-xs font-semibold text-slate-600 underline underline-offset-2 hover:text-navy-900 disabled:opacity-60"
                    >
                      Mark as read
                    </button>
                  ) : null}
                </div>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
