-- =============================================================================
-- Migration 0002 — Reference / lookup tables
--
-- Everything the portal presents as a "choice" lives here, not in the frontend.
-- New applicant categories, support needs, document types, programs and
-- locations can be added later as rows — no application rewrite required.
-- Safe to run more than once (idempotent).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Locations — hierarchical geography (state -> lga -> ward -> community)
--
-- Seeded from official INEC electoral geography (37 states, 774 LGAs,
-- 8,809 wards). Community rows are writable later; for Phase 1 the applicant
-- supplies a free-text community name which the future dashboard can promote
-- into a location row without a redesign.
-- ---------------------------------------------------------------------------
create table if not exists public.locations (
  id          bigint generated by default as identity primary key,
  level       public.location_level not null,
  code        text not null unique,
  name        text not null,
  parent_id   bigint references public.locations(id) on delete restrict,
  -- Denormalised ancestry so analytics can filter by state/LGA with a single join.
  state_id    bigint references public.locations(id) on delete restrict,
  lga_id      bigint references public.locations(id) on delete restrict,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create index if not exists locations_parent_id_idx on public.locations (parent_id);
create index if not exists locations_level_idx     on public.locations (level);
create index if not exists locations_state_id_idx  on public.locations (state_id);
create index if not exists locations_lga_id_idx    on public.locations (lga_id);
create index if not exists locations_name_lower_idx on public.locations (lower(name));

comment on table public.locations is
  'Hierarchical Nigerian geography: state, lga, ward, and (future) community.';

-- ---------------------------------------------------------------------------
-- Applicant categories — drives the public category cards AND the adaptive
-- Step 4 form. `detail_schema` is a JSON array of field descriptors rendered
-- generically by the frontend, so a new category is a row, not a code change.
-- ---------------------------------------------------------------------------
create table if not exists public.applicant_categories (
  id                    bigint generated by default as identity primary key,
  code                  text not null unique,
  name                  text not null,
  short_description     text,
  description           text,
  icon                  text,
  form_variant          text not null default 'generic',
  detail_schema         jsonb not null default '[]'::jsonb,
  sort_order            smallint not null default 0,
  is_active             boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint applicant_categories_detail_schema_is_array
    check (jsonb_typeof(detail_schema) = 'array')
);

comment on column public.applicant_categories.detail_schema is
  'JSON array of {key,label,type,required,options?,placeholder?,help?} descriptors for category-specific fields.';

-- ---------------------------------------------------------------------------
-- Support needs — multi-select on Step 5, structured relational data.
-- ---------------------------------------------------------------------------
create table if not exists public.support_needs (
  id               bigint generated by default as identity primary key,
  code             text not null unique,
  name             text not null,
  description      text,
  requires_details boolean not null default false,
  sort_order       smallint not null default 0,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Document types — what an applicant may upload, and for which category.
-- ---------------------------------------------------------------------------
create table if not exists public.document_types (
  id                    bigint generated by default as identity primary key,
  code                  text not null unique,
  name                  text not null,
  description           text,
  is_required           boolean not null default false,
  -- NULL means "applies to every category"; otherwise a list of category codes.
  applies_to_categories text[],
  max_size_mb           smallint not null default 5,
  sort_order            smallint not null default 0,
  is_active             boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Programs — Phase 1 runs a single program, but the schema supports many so
-- Phase 2/3 can add cohorts, intakes and parallel programs without migration.
-- ---------------------------------------------------------------------------
create table if not exists public.programs (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  name          text not null,
  summary       text,
  description   text,
  status        public.program_status not null default 'DRAFT',
  focus_areas   text[],
  opens_at      timestamptz,
  closes_at     timestamptz,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.programs is
  'Programmes/intakes. Applications reference a program so the platform can run multiple cohorts.';

-- Convenience predicate for "is this program accepting applications right now".
create or replace function public.program_is_open(p public.programs)
returns boolean
language sql
immutable
as $$
  select p.status = 'OPEN'
     and p.is_active
     and (p.opens_at is null or p.opens_at <= now())
     and (p.closes_at is null or p.closes_at >= now());
$$;

-- ---------------------------------------------------------------------------
-- Application statuses — labels, ordering and UI tone live in the database so
-- the applicant timeline is data-driven, not hard-coded in the frontend.
-- ---------------------------------------------------------------------------
create table if not exists public.application_statuses (
  code                 public.application_status primary key,
  label                text not null,
  description          text,
  sort_order           smallint not null,
  tone                 text not null default 'neutral',
  visible_to_applicant boolean not null default true,
  is_terminal          boolean not null default false,
  is_initial           boolean not null default false,
  constraint application_statuses_tone_check
    check (tone in ('neutral', 'info', 'warning', 'success', 'danger', 'progress'))
);

comment on table public.application_statuses is
  'Display metadata for application statuses. Add rows (and an enum value) to extend the lifecycle.';
